### ISSUE TITLE
After level up stats increase were gone

### ISSUE THREAD

**Issue by HWS79** [fcard/AllStatTabs#2]
After a level up the stats increase were gone, as if did not happened, just the regular tab plus level up. After playing for some hours the HIT stat of CRONO was the same (as his HIT stat sucks I was giving him all Speed Tabs with the HIT and EVADE+2). The other tabs did the same.
Used "CT_AllStatsTabs_By2_PowHit.ips - Default stat growth + power tab increases hit".
Did I do something wrong?

**Comment by fcard** [comment]
Oh, that's no good, I didn't notice that was a problem. I will fix it as soon as possible.

**Comment by fcard** [comment]
@HWS79 I think I figured it out, can you try the IPS patches at https://github.com/fcard/AllStatTabs/tree/v1.3/ips and see if it fixes the issue? (any of them will do)

**Comment by HWS79** [comment]
Sorry, still the same. Tested on the first Power Tab (it shows +2 Power +2 Stamina) at Guardia Forest. Crono starts at level 1 with 5 Power and 8 Stamina, used the Tab, went to 7 Power and 10 Stamina, after level up Power was 7 and Stamina was 9 (as if it was with a regular Power Tab and level 2).

**Comment by fcard** [comment]
Odd! It works on mine:
![chrono_lv2](https://user-images.githubusercontent.com/12222927/113582895-4f9fbd80-95ff-11eb-8475-54870d17f34f.png)
Maybe github is being weird. Can you try this file: 
[CT_AllStatTabs_By2.ips.zip](https://github.com/fcard/AllStatTabs/files/6258563/CT_AllStatTabs_By2.ips.zip)
Sorry to bother you, just making sure it works this time.

**Comment by HWS79** [comment]
Yes, now it works! Maybe I was using the wrong one, I was using " CT_AllStatTabs_By2_PowHit ".
Thanks!

**Comment by fcard** [comment]
I will double check to make sure all the ips patches are correct. Thanks for reporting and testing!

**Comment by HWS79** [comment]
Yes, maybe I was doing something wrong. I am not a programmer and very new to Hacking roms. Thanks for all!
